<a href="https://colab.research.google.com/github/numanselalmaz/Breast-Cancer-Classification/blob/master/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [ ]:
# Introduction to Tensors

# -> scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
print(scalar.ndim)
# Get tensor back as Python int
print(scalar.item())

0
7


In [ ]:
# Vector
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [ ]:
# How many dimension ?
print(vector.ndim)

print(vector.shape)

1
torch.Size([2])


In [ ]:
# MATRIX

matrix = torch.tensor([[7,9],
                      [1,3]])

matrix

tensor([[7, 9],
        [1, 3]])

In [ ]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.size())

2
torch.Size([2, 2])
torch.Size([2, 2])


In [ ]:
# Tensor

tensor = torch.tensor([[[1,2,3], [12,3,3], [12,312,123]]])
tensor

tensor([[[  1,   2,   3],
         [ 12,   3,   3],
         [ 12, 312, 123]]])

In [ ]:
print(tensor.ndim)
print(tensor.shape)
print(tensor.size())

3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])


In [ ]:
tensor[0][0]

tensor([1, 2, 3])

# Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [ ]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3,  4)
random_tensor

tensor([[0.6549, 0.0480, 0.2470, 0.8077],
        [0.8020, 0.6767, 0.8818, 0.5678],
        [0.2888, 0.2525, 0.9477, 0.8353]])

In [ ]:
random_tensor2 = torch.rand(3, 4, 3)
random_tensor2

tensor([[[0.0235, 0.7063, 0.5276],
         [0.0388, 0.5884, 0.2356],
         [0.4245, 0.5925, 0.2651],
         [0.9780, 0.5862, 0.1854]],

        [[0.2876, 0.9711, 0.1377],
         [0.3181, 0.4707, 0.1626],
         [0.8116, 0.4084, 0.4078],
         [0.7050, 0.1870, 0.5734]],

        [[0.0750, 0.6249, 0.6401],
         [0.0912, 0.2959, 0.0288],
         [0.9477, 0.4687, 0.0124],
         [0.3924, 0.7171, 0.9533]]])

In [ ]:
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype
zeros.dtype

torch.float32

In [ ]:
### Creating a range of tensors and tensors-like

# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
zero_to_thousand = torch.arange(start=0, end=1001, step=100)
zero_to_thousand

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Note:
      Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
      
      1. Tensors not right datatype
      2. Tensors not right shape
      3. Tensors not on the right device
      

In [ ]:
# Tensor datatypes
float_32_tensor = torch.tensor([3.,6. ,9.], dtype = None)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.,6. ,9.], dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = torch.tensor([3.,6. ,9.], dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = torch.tensor([3.,6. ,9.],
                               dtype = torch.float16, # what datatype is the tensor
                               device = None, # What device is your tensor on
                               requires_grad=False # Whether or not to track gradients with this tensors operations
                               )
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
int_32_tensor = torch.tensor([1,2,3], dtype = torch.int32)
int_32_tensor.dtype

torch.int32

# Note

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype

2. Tensors not right shape -to get shape from a tensor, can use tensor.shape

3. Tensors not on the right device - to get device from a tensor, can use tensor.device

# Manipulatinh Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 20

tensor([21, 22, 23])

In [ ]:
# Subtraction
tensor - 20

tensor([-19, -18, -17])

In [ ]:
# Division
tensor / 13

tensor([0.0769, 0.1538, 0.2308])

# Matrix multiplication

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix mutliplication need to satisfy:
  1. The inner dimension must match :
      * (3, 2) @ (3, 2) won't work
      * (2, 3) @ (3, 2) will work
      * (3, 2) @ (2, 3) will work

  2. The resulting matrix has the shape of the outer dimensions :
      * (2, 3) @ (3, 2) -> (2, 2)
      * (3, 2) @ (2, 3) -> (3, 3)

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

# One of the most common errors in deep learning : shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                         [5, 6]])

tensor_B  = torch.tensor ([[7, 10],
                           [8, 11],
                           [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape errors, we can manipulate the shape of one of our tensors using a transpose
A transpose switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {torch.mm(tensor_A, tensor_B.T)} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

# Finding the min, max, sum, etc(tensor aggregation)

In [ ]:
n = torch.arange(0, 101, 10)
n

In [ ]:
# min
torch.min(n), n.min()

In [ ]:
# max
torch.max(n), n.max()

In [ ]:
# mean
torch.mean(n.type(torch.float32)), n.type(torch.float32).mean()

In [ ]:
# sum
torch.sum(n), n.sum()

In [ ]:
# Find the position in tensor that has the minimum value with argmin()
torch.argmin(n), n.argmin()

In [ ]:
# Find the position in tensor that  has the maximum value with argmax()
torch.argmax(n), n.argmax()

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other (vstack)

* Squeeze - remove all "1" dimensions from a tensor

* Unsqueeze - add a "1" dimension to a target tensor

* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch

y = torch.arange(1. , 10.)
y, y.shape

In [ ]:
y_reshaped = y.reshape(3, 3)
y_reshaped, y_reshaped.shape

x.view, orijinal Tensor'un bellekteki yapısını değiştirmeden farklı bir şekle bürünmesini sağlar. Bu fonksiyon, yalnızca orijinal Tensor'ün bellekte ardışık (contiguous) bir şekilde düzenlenmiş olması durumunda çalışır. Eğer Tensor ardışık değilse, view fonksiyonu bir hata verir.

x.reshape, Tensor'u yeniden şekillendirmek için daha esnek bir fonksiyondur. Eğer gerekirse, Tensor'u ardışık hale getirmek için bellekte yeni bir kopya oluşturur. Bu nedenle, x.reshape genellikle x.view'a göre daha esnektir, çünkü ardışık olmayan Tensor'lar için de çalışabilir.



In [ ]:
# Change the view
z = y.view(1, 9)
z, z.shape

In [ ]:
# z'deki değişiklik neden y'yi etkiliyorun cevabı ardışık olduğu için aynı yerde tutulur x ile.
z[:, 1] = 12
z, y

In [ ]:
# stack horizotal
x_stacked_h = torch.stack([y, y, y, y], dim=0) # or torch.hstack(....)
x_stacked_h, x_stacked_h.shape

In [ ]:
# stack vertical
x_stacked_v = torch.stack([y, y, y, y], dim = 1)
x_stacked_v, x_stacked_v.shape

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = y.reshape(9, 1)

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [ ]:
# Add an extra dimension with unsqueeze

y_unsqueezed = y.unsqueeze(dim = 0)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

In [ ]:
# permute
a = torch.rand(size=(224, 224, 3))

a_permuted = a.permute(2, 0, 1)
a.shape, a_permuted.shape

# Indexing (selectin data from tensors)

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

In [ ]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

In [ ]:
x[:, 0]

In [ ]:
x[:, :, 0]

# Pytorch tensors & NumPy

 * torch.from_numpy(ndarray) - NumPy array -> Pytorch tensor

 * torch.Tensor.numpy() - PyTorch tensor -> NumPy array


In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

* Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype(as above).

However, many PyTorch calculations default to using (float32).

So if you want to convert your NumPy array (float64)  -> PyTorch tensor (float64) -> Pt

In [ ]:
# array ve ondan türetilmiş tensor farklı belleklerde depolandığından kaynaklı arrayde ki değişim tensoru
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducibility

In [ ]:
# Yeniden üretilebilirlik yok
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5448, 0.2635, 0.0415, 0.5270],
        [0.0381, 0.2013, 0.3412, 0.7080],
        [0.4298, 0.8726, 0.4569, 0.4216]])

Tensor B:
tensor([[0.2891, 0.1054, 0.3986, 0.7686],
        [0.0560, 0.2956, 0.8782, 0.1480],
        [0.2162, 0.3343, 0.6936, 0.5973]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Yeniden üretilebilirlik var

RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)


torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Getting PyTorch to run on the GPU

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

# Putting tensors (and models) on the GPU

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = torch.tensor([1,2 ,3]).to(device)

print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0
